# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "172.16.10.103"
    config.vm.hostname = "worker-2.xtl"
  
    config.vm.provider "virtualbox" do |vb|
       vb.name = "worker-2.xtl"
       vb.cpus = 1
       vb.memory = "2048"
    end
     
    config.vm.provision "shell", path: "./../install-docker-kube.sh"
  
    config.vm.provision "shell", inline: <<-SHELL
    
      echo "root password"
      echo "123" | passwd --stdin root
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd
  
  
  cat >>/etc/hosts<<EOF
  172.16.10.100 master-1.xtl
  172.16.10.101 master-2.xtl
  172.16.10.102 worker-1.xtl
  172.16.10.103 worker-2.xtl
  172.16.10.104 worker-3.xtl
  172.16.10.105 nsf
  EOF
  
      
    SHELL
  end