# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "172.16.10.102"
    config.vm.hostname = "worker1"
  
    config.vm.provider "virtualbox" do |vb|
       vb.name = "worker1"
       vb.cpus = 1
       vb.memory = "2048"
    end
     
    config.vm.provision "shell", path: "./../install-docker-kube.sh"
  
    config.vm.provision "shell", inline: <<-SHELL
    
      echo "root password"
      echo "123" | passwd --stdin root
      echo "Creating sysadmin user"
      useradd sysadmin
      echo "sysadmin password"
      echo "123" | passwd --stdin sysadmin
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd
  
  
  cat >>/etc/hosts<<EOF
  172.16.10.100 master1
  172.16.10.101 master2
  172.16.10.107 master3
  172.16.10.102 worker1
  172.16.10.103 worker2
  172.16.10.104 worker3
  172.16.10.105 rancher
  172.16.10.106 cicd
  EOF
  
      
    SHELL
  end